### ISSUE TITLE
Unblessed Error in Console When Moving Image

### ISSUE THREAD

**Issue by sganz** [punkave/apostrophe#1012]
Was messing with the getting started project and I added a Rich text and an Image to the page. Then moved the image over the text with the drag handlesd I saw the message in the console. 

Running on Mint 18 Linux with FF version 55.0.2

This is my `packages.json` for the sample project -
```
{
  "name": "aposCMS",
  "version": "2.0.0",
  "description": "Minimal aposCMS",
  "main": "app.js",
  "scripts": {
    "start": "node app.js"
  },
  "repository": {
    "type": "git",
    "url": ""
  },
  "author": "P'unk Avenue",
  "license": "MIT",
  "dependencies": {
    "apostrophe": "^2.36.0"
  }
}

```

```
Error: unblessed
    at /home/sandy/aposCMS/node_modules/apostrophe/lib/modules/apostrophe-areas/lib/routes.js:158:19
    at /home/sandy/aposCMS/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:86:20
    at /home/sandy/aposCMS/node_modules/async/lib/async.js:181:20
    at iterate (/home/sandy/aposCMS/node_modules/async/lib/async.js:262:13)
    at Object.async.forEachOfSeries.async.eachOfSeries (/home/sandy/aposCMS/node_modules/async/lib/async.js:281:9)
    at Object.async.forEachSeries.async.eachSeries (/home/sandy/aposCMS/node_modules/async/lib/async.js:214:22)
    at /home/sandy/aposCMS/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:85:24
    at Layer.handle [as handle_request] (/home/sandy/aposCMS/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/sandy/aposCMS/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/home/sandy/aposCMS/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/sandy/aposCMS/node_modules/express/lib/router/layer.js:95:5)
    at /home/sandy/aposCMS/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/home/sandy/aposCMS/node_modules/express/lib/router/index.js:335:12)
    at next (/home/sandy/aposCMS/node_modules/express/lib/router/index.js:275:10)
    at serveStatic (/home/sandy/aposCMS/node_modules/serve-static/index.js:75:16)
    at Layer.handle [as handle_request] (/home/sandy/aposCMS/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by boutell** [comment]
Just tried this in a new Apostrophe project and was not able to reproduce it. We did make recent changes to cut down on unblessed errors, so try an "npm update" and restart.

**Comment by sganz** [comment]
I did try `npm update` and had the same results. I'm still pretty green when working with Node, so I'm going to scrap the current test and reinstall it all from scratch on a new VM and see if it does it again.

Thanks
Sandy
