### ISSUE TITLE
template issue on launching

### ISSUE THREAD

**Issue by JoshuaSeidel** [punkave/apostrophe#1072]
got my docker container up. when i go to the site it errors out and in the logs i see:

2017-10-30T14:55:03.626432702Z e.stack:  Error: template not found: pages/home.html
2017-10-30T14:55:03.626459840Z     at createTemplate (/app/node_modules/nunjucks/src/environment.js:206:31)
2017-10-30T14:55:03.626464130Z     at next (/app/node_modules/nunjucks/src/lib.js:210:13)
2017-10-30T14:55:03.626475066Z     at handle (/app/node_modules/nunjucks/src/environment.js:252:25)
2017-10-30T14:55:03.626477926Z     at /app/node_modules/nunjucks/src/environment.js:263:21
2017-10-30T14:55:03.626480406Z     at next (/app/node_modules/nunjucks/src/lib.js:207:13)
2017-10-30T14:55:03.626482951Z     at Object.exports.asyncIter (/app/node_modules/nunjucks/src/lib.js:214:5)
2017-10-30T14:55:03.626485491Z     at new_cls.getTemplate (/app/node_modules/nunjucks/src/environment.js:242:17)
2017-10-30T14:55:03.626488103Z     at Object.self.renderBody (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:309:24)
2017-10-30T14:55:03.626490704Z     at Object.self.renderForModule (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:176:19)
2017-10-30T14:55:03.626493386Z     at Object.self.render (/app/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:186:34)
2017-10-30T14:55:03.626495949Z     at Object.self.renderPageForModule (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:662:28)
2017-10-30T14:55:03.626498650Z     at /app/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:362:31
2017-10-30T14:55:03.626501223Z     at /app/node_modules/async/lib/async.js:726:13
2017-10-30T14:55:03.626503778Z     at /app/node_modules/async/lib/async.js:52:16
2017-10-30T14:55:03.626506241Z     at /app/node_modules/async/lib/async.js:269:32
2017-10-30T14:55:03.626508807Z     at /app/node_modules/async/lib/async.js:44:16
2017-10-30T14:55:03.626923427Z :: 2017-10-30T14:55:03+0000: template error at /
2017-10-30T14:55:03.626932704Z Current user: none
2017-10-30T14:55:03.626935450Z Error: template not found: pages/home.html
2017-10-30T14:55:03.626938035Z     at createTemplate (/app/node_modules/nunjucks/src/environment.js:206:31)
2017-10-30T14:55:03.626940734Z     at next (/app/node_modules/nunjucks/src/lib.js:210:13)
2017-10-30T14:55:03.626943355Z     at handle (/app/node_modules/nunjucks/src/environment.js:252:25)
2017-10-30T14:55:03.626945984Z     at /app/node_modules/nunjucks/src/environment.js:263:21
2017-10-30T14:55:03.626948546Z     at next (/app/node_modules/nunjucks/src/lib.js:207:13)
2017-10-30T14:55:03.626951024Z     at Object.exports.asyncIter (/app/node_modules/nunjucks/src/lib.js:214:5)
2017-10-30T14:55:03.626953631Z     at new_cls.getTemplate (/app/node_modules/nunjucks/src/environment.js:242:17)
2017-10-30T14:55:03.626956198Z     at Object.self.renderBody (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:309:24)
2017-10-30T14:55:03.626958852Z     at Object.self.renderForModule (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:176:19)
2017-10-30T14:55:03.626961439Z     at Object.self.render (/app/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:186:34)
2017-10-30T14:55:03.626964046Z     at Object.self.renderPageForModule (/app/node_modules/apostrophe/lib/modules/apostrophe-templates/index.js:662:28)
2017-10-30T14:55:03.626967043Z     at /app/node_modules/apostrophe/lib/modules/apostrophe-module/index.js:362:31
2017-10-30T14:55:03.626975030Z     at /app/node_modules/async/lib/async.js:726:13
2017-10-30T14:55:03.626977668Z     at /app/node_modules/async/lib/async.js:52:16
2017-10-30T14:55:03.626980226Z     at /app/node_modules/async/lib/async.js:269:32
2017-10-30T14:55:03.626982688Z     at /app/node_modules/async/lib/async.js:44:16

ideas on what im missing?

**Comment by boutell** [comment]
I think you did something funky in lib/modules which caused your earlier problem, and then removed everything in lib/modules, including lib/modules/apostrophe-pages/views/pages. I recommend that you just generate another boilerplate project.

For how-to questions and general "it doesn't work but I'm not sure if this is a bug..." questions, please use stackoverflow and tag them apostrophe-cms.

Thanks!
