### ISSUE TITLE
Error, Cannot find module 'Bluebird in 'apostrophe-pages/lib/api.js when starting a new test-project (following tutorial - node app.js)

### ISSUE THREAD

**Issue by julianloigsl** [punkave/apostrophe#1130]
Try to start new test-project (following tutorial - node app.js) got below error. Looks like it is affected by recent changes of the api.js file in apostrophe-pages module. 

Error while constructing the apostrophe-pages module
Error: Cannot find module 'Bluebird'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/ec2-user/test-project/node_modules/apostrophe/lib/modules/apostrophe-pages/lib/api.js:4:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at construct (/home/ec2-user/test-project/node_modules/apostrophe/lib/modules/apostrophe-pages/index.js:264:5)
    at construct (/home/ec2-user/test-project/node_modules/moog/index.js:266:21)
    at /home/ec2-user/test-project/node_modules/moog/index.js:276:22
    at iterate (/home/ec2-user/test-project/node_modules/moog/node_modules/async/lib/async.js:146:13)

**Comment by julianloigsl** [comment]
In Redhat 7 Linux environment.

**Comment by julianloigsl** [comment]
Try to modify the ~/test-project/node_modules/apostrophe/lib/modules/apostrophe-pages/lib/api.js file as below (from Bluebird -> bluebird), then node app.js can start. I guess it is case sensitive in Linux environment.

line 4: var Promise = require('bluebird');

**Comment by boutell** [comment]
Yep. Will fix later tonight and get Linux ci working again.

**Comment by boutell** [comment]
This issue has been fixed. Thanks.
