### ISSUE TITLE
Unable to create add user under ubuntu/kubuntu

### ISSUE THREAD

**Issue by darsparx** [punkave/apostrophe#1145]
I think I installed everything including the cli from npm and everything else but it just doesn't want to let me create a project. It just gives out this error:

`module.js:471
    throw err;
    ^

Error: Cannot find module 'apostrophe'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/kaosine/Sites/personal-portfolio/app.js:3:33)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
`

after running "node app.js apostrophe-users:add admin admin". I've never had so much trouble in doing something like this and don't recall having so many issues when I did the setup on windows I think(on a computer I've sent off for repairs).

**Comment by boutell** [comment]
You need to run "npm install"

**Comment by darsparx** [comment]
I did, it apparently fixed itself after a reboot or after I did "npm install apostrophe" not sure. It's strange.....I followed the guide on the website to a T to make sure everything was properly installed and everything and it just didn't want to work. Not in this VM and definitely not on mac(which is why I switched to the VM since I've always had less trouble under actual linux)

**Comment by boutell** [comment]
Odd. If you get a chance to try this in a fresh folder and copy and paste any errors let us know, otherwise closing for housekeeping. We haven't had any similar reports and are rolling it out on Linux boxes regularly for our own deployments.
