### ISSUE TITLE
[apostrophe] No session secret provided, please set `secret` for apostrophe-express module

### ISSUE THREAD

**Issue by graphicbeacon** [punkave/apostrophe#660]
Hello @boutell, I originally posted this on the Google+ group but was asked to recreate this here and assign to you. Your help is greatly appreciated.

I am in the process of getting apostrophe to run by following the instructions detailed here: 
http://apostrophenow.org/tutorials/getting-started/creating-your-first-project.html

I have installed the cli tool and created my first project. However running 'node app.js' throws this exception:

```
WARNING: No session secret provided, please set `secret` for apostrophe-express module in app.js
fs.js:897
  return binding.symlink(preprocessSymlinkDestination(target, type, path),
                 ^

Error: EPERM: operation not permitted, symlink 'C:\Users\admin\Desktop\Projects\apos-project\node_modules\apostrophe\lib\modules\apostrophe-assets\public' -> 'C:\Users\admin\Desktop\Projects\apos-project\public\modules\apostrophe-assets'
    at Error (native)
    at Object.fs.symlinkSync (fs.js:897:18)
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\apostrophe\lib\modules\apostrophe-assets\index.js:403:14
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\lodash\index.js:3073:15
    at baseForOwn (C:\Users\admin\Desktop\Projects\apos-project\node_modules\lodash\index.js:2046:14)
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\lodash\index.js:3043:18
    at Function.<anonymous> (C:\Users\admin\Desktop\Projects\apos-project\node_modules\lodash\index.js:3346:13)
    at self.symlinkModules (C:\Users\admin\Desktop\Projects\apos-project\node_modules\apostrophe\lib\modules\apostrophe-assets\index.js:384:9)
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:718:13
    at iterate (C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:262:13)
    at async.forEachOfSeries.async.eachOfSeries (C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:281:9)
    at _parallel (C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:717:9)
    at Object.async.series (C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:739:9)
    at Object.self.afterInit (C:\Users\admin\Desktop\Projects\apos-project\node_modules\apostrophe\lib\modules\apostrophe-assets\index.js:348:20)
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\apostrophe\index.js:91:25
    at C:\Users\admin\Desktop\Projects\apos-project\node_modules\async\lib\async.js:181:20
```

I attempted to add configuration for apostrophe-express by adding the code below to the app.js config object, but still not working:

```
var apos = require('apostrophe')({
    //...
    modules: {
        //...
        'apostrophe-express': {
              secret: 'secret password'
        }
    }
});
```

I also tried:
```
var apos = require('apostrophe')({
    //...
    secret: 'secret password'
});
```

I am investigating ApostropheCMS as a possible content management solution for the company I work at. Any help would be really appreciated.

Many thanks in advance.

**Comment by boutell** [comment]
As was just announced in the google group, this is fixed in Apostrophe 2.1.1, which is now compatible with Windows when not running as administrator.
