### ISSUE TITLE
Setup failure caused by missing module 'replace'

### ISSUE THREAD

**Issue by ggcaponetto** [punkave/apostrophe#885]
Following the latest instructions available i encountered the following problem:

1. <code>apostrophe create test-project</code>
```
Error: Cannot find module 'replace'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/apostrophe-cli/lib/commands/create.js:2:15)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
```

Do i need to install the module 'replace' as a peer dependency? Is there any other documentation that can help me with the setup?

I'm running : 
1. npm --v 4.2.0
1. node -v 6.9.4
1. mac osx 10.12.3

__update__: the problem seems to be present only for apostrophe-cli@2.1.0 and not for apostrophe-cli@2.0.1

**Comment by edson-gaspar** [comment]
+1
On my macOS, same configuration above.

**Comment by napcoder** [comment]
+1

1. npm --version 4.2.0
1. node --version v6.10.3
1. mac osx 10.12.4

**Comment by boutell** [comment]
Fixed, sorry for the hassle. Please `npm install -g apostrophe-cli`
